-- QUERY #1
-- The following query finds the Flight ID  (flightid, flightaircraftno, departualairportcode, arrivalairportcode, arrivaltime, departuretime)
-- in Which female passangers generated the maximux revenue . This can be done to understand which route is more preferred by females.
SELECT flightid, flightaircraftno, departualairportcode, arrivalairportcode, arrivaltime, departuretime
FROM S20_5_flight_Schedule f
WHERE f.flightID  in 
    (SELECT B.flightID
    FROM s20_5_booking B, s20_5_passanger P
    WHERE B.passangerID = P.passangerid AND P.gender='f'
    GROUP BY B.flightID
    HAVING SUM(B.Airfare) >= ALL(SELECT SUM(B.Airfare)
                                FROM s20_5_booking B, s20_5_passanger P
                                WHERE B.passangerID = P.passangerid AND P.gender='f'
                                GROUP BY B.flightID));                             

-- SPECIFIC RANGE OF TIME
--SELECT flightid, flightaircraftno, departualairportcode, arrivalairportcode, arrivaltime, departuretime
--FROM S20_5_flight_Schedule f
--WHERE f.departuretime > '01-JAN-2020 12.00.00 AM' 
--    AND f.departuretime < '04-JAN-2020  12.00.00 AM'  AND f.flightID  in 
--    (SELECT B.flightID
--    FROM s20_5_booking B, s20_5_passanger P
--    WHERE B.passangerID = P.passangerid AND P.gender='f'
--    GROUP BY B.flightID
--    HAVING SUM(B.Airfare) >= ALL(SELECT SUM(B.Airfare)
--                                FROM s20_5_booking B, s20_5_passanger P
--                                WHERE B.passangerID = P.passangerid AND P.gender='f'
--                                GROUP BY B.flightID));                             


-- QUERY #2
-- The following query will generate a summary report of revenue generated by each flightID
-- based on gender and class of travel. This can be done to understand the class of travel preferred by gender
SELECT  
    B.FlightID, 
    gender,
    Classoftravel,
    Count(gender) as PassangerCount, 
    SUM(B.airfare) as Revenue
FROM  s20_5_booking B 
    Join s20_5_flight_schedule F on B.FlightID = F.flightID
    Join S20_5_PASSANGER P on P.passangerID = B.PassangerID
group by rollup(B.FlightID, gender, Classoftravel);


-- QUERY #3
-- The following query will print out the traffic of each airport.
-- This can be done to understand which airport is the most busiet.
SELECT 
    Departualairportcode,
    arrivalairportcode,
    count(PASSANGERID)
FROM  s20_5_booking B
    Natural Join s20_5_flight_schedule F 
    Natural Join S20_5_PASSANGER P
Group By CUBE(Departualairportcode, arrivalairportcode)
Order By Departualairportcode, arrivalairportcode;
